### ISSUE TITLE
`1.19.3^ Crash` Loading a world with Clean Tooltips 1.1 on fabric 1.19.3^ crashes

### ISSUE THREAD

**Issue by zndrmn** [stal111/Clean-Tooltips#2]
`java.lang.NoSuchFieldError: field_11160`

Minecraft 1.19.3
Fabric 0.14.19
Fabric API 0.76.0
ForgeConfigAPI 5.0.11
Clean Tooltips 1.1

[latest.log](https://gist.github.com/zndrmn/139f8372413760358ed647e3b5a62e63#file-gistfile1-txt)

**Comment by stal111** [comment]
It's only available for 1.19.2 for now.

**Comment by stal111** [comment]
Versions for 1.19.4 and 1.20 are available now.
