### ISSUE TITLE
(Compatibility) Enchantment Descriptions

### ISSUE THREAD

**Issue by muon-rw** [stal111/Clean-Tooltips#4]
This mod overwrites Enchantment Descriptions - On gear this makes sense as it compresses the size of the tooltip significantly. 

Would it maybe be possible to show enchantment descriptions instead on books, or somehow integrate the two otherwise?

If not, maybe you could note the incompatibility somewhere.

**Comment by afloofflam** [comment]
Ditto. Just realized why none of them have been appearing and came here. Seconding showing the descriptions in the book or via JEI/REI.

**Comment by stal111** [comment]
Version 1.3 should add compatibility with Enchantment Descriptions on Enchanted Books.

**Comment by afloofflam** [comment]
Works like a charm! Thank you for the quick work and an awesome mod.
